apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: tidy-discipline-407811
      auth:
        workloadIdentity:
          clusterName: cluster-1
          clusterProjectID: tidy-discipline-407811
