---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.4
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets@${PROJECT_ID}.iam.gserviceaccount.com
    nodeSelector:
      iam.gke.io/gke-metadata-server-enabled: "true"
  install:
    createNamespace: true