---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-stagging
spec:
  refreshInterval: 1m           
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: eso-stagging
    creationPolicy: Owner
  data:
  - secretKey: test
    remoteRef:
      key: test