apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store-stagging
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: lmk-secrets-shrd-yvd7ff2153q0b