---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-crs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m
  path: ./infrastructure/cert-manager/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system