---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 1m
  path: ./deploy/charts/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: cert-manager