apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 5m
  values:
    controller:
      service:
        externalTrafficPolicy: "Local"
        loadBalancerIP: ${lb_ip}
      config:
        use-gzip: "true"
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "true"
      metrics:
        enabled: "true"
        serviceMonitor:
          enabled: "true"
          additionalLabels:
            release: prometheus-operator
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  