apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: projectid
      auth:
        workloadIdentity:
          clusterLocation: europe-west3
          clusterName: cluster
          clusterProjectID: tidy-discipline-407811
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets