apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  namespace: test
spec:
  refreshInterval: 1m           
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: eso-test
    creationPolicy: Owner
  data:
  - secretKey: test
    remoteRef:
      key: test