apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: eso-test
    creationPolicy: Owner
  data:
  - secretKey: test
    remoteRef:
      key: test